#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
. "${SLOTH_PATH:-${DOTLY_PATH:-}}/scripts/core/src/_main.sh"
dot::load_library "templating.sh" "core"

##? Create the dotfiles structure
##?
##? Usage:
##?    create -h | --help
##?    create -v | --version
##?    create [<dotfiles_path>]
##?
#? v2.0.1
if [[ $1 == "-v" || $1 == "--version" || $1 == "-h" || $1 == "--help" ]]; then
  docs::parse "$@"
fi

DOTFILES_PATH="${1:-${DOTFILES_PATH:-}}"

[[ -z "$DOTFILES_PATH" ]] && output::error "DOTFILES_PATH not found" && exit 1

if ! mkdir -p "$DOTFILES_PATH" 2> /dev/null; then
  output::error "Could not create \`${DOTFILES_PATH}\`" && exit 1
fi

if [ ! -d "${DOTFILES_PATH}/shell" ]; then
  cp -r "${SLOTH_PATH:-${DOTLY_PATH:-}}/dotfiles_template/"* "${DOTFILES_PATH}/"

  "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" core loader --modify

  log::success "Done!"
else
  log::note "dotfiles already created, ignoring"
fi
