#!/usr/bin/env bash
#shellcheck disable=SC2016

set -euo pipefail

[[ -z "${SLOTH_PATH:-${DOTLY_PATH:-}}" ]] && exit 1

#shellcheck disable=SC1091
. "${SLOTH_PATH:-${DOTLY_PATH:-}}/scripts/core/src/_main.sh"
dot::load_library "templating.sh" "core"

# Define DOTFILES_PATH and SLOTH_PATH values in .bashrc and .zshrc
DOTFILES_PATH_VALUE="${DOTFILES_PATH//$HOME/\${HOME\}}"
SLOTH_PATH="${SLOTH_PATH:-${DOTLY_PATH:-}}"

# Standalone install with brew
if
  command -v brew &> /dev/null &&
    brew list gtrabanco/tools/dot 2> /dev/null &&
    [[ -d "$(brew --prefix gtrabanco/tools/dot 2> /dev/null)" ]]
then
  SLOTH_PATH_VALUE="$(brew --prefix gtrabanco/tools/dot 2> /dev/null)"
# Regular install as git repository in DOTFILES_PATH or standalone install from source
elif [[ -d "${DOTFILES_PATH}/modules/sloth" ]]; then
  SLOTH_PATH_VALUE="\${DOTFILES_PATH}/modules/sloth"
elif [[ -d "${DOTFILES_PATH}/modules/dotly" ]]; then
  SLOTH_PATH_VALUE="\${DOTFILES_PATH}/modules/dotly"
else
  output::error ".Sloth path could not be detected"
  output::answer "If you know the path use this command as:"
  output::write "\`SLOTH_PATH=/path/to/.sloth dot core loader --modify\`"
  exit 1
fi

zshrc_load() {
  case "${1:-both}" in
    "zshenv")
      echo
      echo '###### .Sloth Variables ######'
      if [[ -n "${DOTFILES_PATH_VALUE}" ]]; then
        echo "export DOTFILES_PATH=\"${DOTFILES_PATH_VALUE}\""
      else
        echo "# When you have setup your custom dotfiles path modify next value and uncoment it"
        echo "# export DOTFILES_PATH=\"\${HOME}/.dotfiles\""
      fi
      echo "export SLOTH_PATH=\"${SLOTH_PATH_VALUE}\""
      echo "export DOTLY_PATH='\${SLOTH_PATH:-}'"
      echo 'export ZIM_HOME="${SLOTH_PATH:-${DOTLY_PATH:-}}/modules/zimfw"'
      echo '###### End of .Sloth Variables ######'
      echo
      ;;
    "zshrc")
      echo
      echo '###### .Sloth Loader ######'
      echo 'if [[ -f "${SLOTH_PATH:-${DOTLY_PATH:-}}/shell/init-sloth.sh" ]]'
      echo 'then'
      echo '  #shellcheck disable=SC1091'
      echo '  . "${SLOTH_PATH:-${DOTLY_PATH:-}}/shell/init-sloth.sh"'
      echo 'else'
      echo '  echo "\033[0;31m\033[1mSLOTH Loader could not be found, check \$DOTFILES_PATH & \$SLOTH_PATH variables\033[0m"'
      echo 'fi'
      echo '###### End of .Sloth loader ######'
      echo
      ;;
    *)
      echo 'You need to create or modify two different files'
      echo '--------------- BEGIN .zshenv file ---------------'
      echo
      zshrc_load "zshenv"
      echo
      echo '---------------  END .zshenv file  ---------------'
      echo
      echo
      echo
      echo '--------------- BEGIN .zshrc file ---------------'
      echo
      zshrc_load "zshrc"
      echo
      echo '---------------  END .zshrc file  ---------------'
      echo
      ;;
  esac
}

bashrc_load() {
  case "${1:-both}" in
    "vars")
      echo
      echo '###### .Sloth Variables ######'
      if [[ -n "${DOTFILES_PATH_VALUE}" ]]; then
        echo "export DOTFILES_PATH=\"${DOTFILES_PATH_VALUE}\""
      else
        echo "# When you have setup your custom dotfiles path modify next value and uncoment it"
        echo "# export DOTFILES_PATH=\"\${HOME}/.dotfiles\""
      fi
      echo "export SLOTH_PATH=\"${SLOTH_PATH_VALUE}\""
      echo "export DOTLY_PATH='\${SLOTH_PATH:-}'"
      echo '###### End of .Sloth Variables ######'
      echo
      ;;
    "loader")
      echo
      echo '###### .Sloth Loader ######'
      echo 'if [[ -f "${SLOTH_PATH:-${DOTLY_PATH:-}}/shell/init-sloth.sh" ]]'
      echo 'then'
      echo '  #shellcheck disable=SC1091'
      echo '  . "${SLOTH_PATH:-${DOTLY_PATH:-}}/shell/init-sloth.sh"'
      echo 'else'
      echo '  echo "\033[0;31m\033[1mSLOTH Loader could not be found, check \$DOTFILES_PATH & \$SLOTH_PATH variables\033[0m"'
      echo 'fi'
      echo '###### End of .Sloth loader ######'
      echo
      ;;
    *)
      bashrc_load "vars"
      bashrc_load "loader"
      ;;
  esac
}

check_has_loader() {
  local -r file="${1:-}"
  if [[ -n "$file" && -f "${file}" ]]; then
    grep -q 'shell/init-sloth.sh"$' "$file"
  else
    return 1
  fi
}

check_file_has_var_defined() {
  local -r file="${1:-}"
  local -r var="${2:-}"
  local value="${3:-.*}"
  [[ -z "$file" || ! -f "${file}" || -z "$var" ]] && return 1

  if [[ -n "$value" ]]; then
    grep --quiet --extended-regexp "${var}=\"?${value//\$/\\\$}\"?( |;|$)" "$file"
  fi
}

setup_bashrc() {
  local -r rcfile="${DEFAULT_BASHRC_FILE:-${HOME}/.bashrc}"
  command -p touch "$rcfile"
  [[ ! -f "$rcfile" ]] && return 1

  if check_file_has_var_defined "$rcfile" "DOTFILES_PATH" && [[ -n "${DOTFILES_PATH_VALUE:-}" ]]; then
    templating::modify_bash_file_variable "$rcfile" "DOTFILES_PATH" "$DOTFILES_PATH_VALUE"
  fi

  if check_file_has_var_defined "$rcfile" "SLOTH_PATH"; then
    templating::modify_bash_file_variable "$rcfile" "SLOTH_PATH" "$SLOTH_PATH_VALUE"
  fi

  if ! check_file_has_var_defined "$rcfile" "DOTFILES_PATH" && ! check_file_has_var_defined "$rcfile" "SLOTH_PATH"; then
    bashrc_load "vars" | tee -a "$rcfile"
  fi

  if ! check_has_loader "$rcfile"; then
    bashrc_load "loader" | tee -a "$rcfile"
  fi

  if
    [[ -f "${HOME}/.bash_profile" ]] &&
      { ! grep -q '. "$HOME/.bashrc"' "${HOME}/.bash_profile" || ! grep -q '. "${HOME}/.bashrc"' "${HOME}/.bash_profile"; }
  then
    echo '. "${HOME}/.bashrc"' >> "${HOME}/.bash_profile"
  fi

  if check_has_loader "$rcfile" && check_file_has_var_defined "$rcfile" "DOTFILES_PATH" && check_file_has_var_defined "$rcfile" "SLOTH_PATH"; then
    output::solution ".Sloth loader added in \`${rcfile//$HOME/\${HOME\}}\`"
    return 0
  fi

  output::error "Could not add .Sloth loader or variables in \`${rcfile}\`"
  output::answer "Check the file, maybe add manually the loader should fix this."
  return 1
}

setup_zsh() {
  local -r zshrcfile="${DEFAULT_ZSHRC_FILE:-${HOME}/.zshrc}"
  local -r zshenvfile="${DEFAULT_ZSHENV_FILE:-${HOME}/.zshenv}"
  command -p touch "$zshrcfile"
  command -p touch "$zshenvfile"
  [[ ! -f "$zshrcfile" || ! -f "$zshenvfile" ]] && return 1

  if check_file_has_var_defined "$zshenvfile" "DOTFILES_PATH" && [[ -n "${DOTFILES_PATH_VALUE:-}" ]]; then
    templating::modify_bash_file_variable "$zshenvfile" "DOTFILES_PATH" "$DOTFILES_PATH_VALUE"
  fi

  if check_file_has_var_defined "$zshenvfile" "SLOTH_PATH"; then
    templating::modify_bash_file_variable "$zshenvfile" "SLOTH_PATH" "$SLOTH_PATH_VALUE"
  fi

  if ! check_file_has_var_defined "$zshenvfile" "DOTFILES_PATH" && ! check_file_has_var_defined "$zshenvfile" "SLOTH_PATH"; then
    zshrc_load "zshenv" | tee -a "$zshenvfile"
  fi

  if ! check_has_loader "$zshrcfile"; then
    zshrc_load "zshrc" | tee -a "$zshrcfile"
  fi

  if
    [[ -f "${HOME}/.zlogin" ]] &&
      { ! grep -q '. "$ZIM_HOME/login_init.zsh" -q &!' "${HOME}/.zlogin" || ! grep -q '. "${ZIM_HOME}/login_init.zsh" -q &!' "${HOME}/.zlogin"; }
  then
    echo '. "${ZIM_HOME}/login_init.zsh" -q &!' >> "${HOME}/.zlogin"
  fi

  if check_has_loader "$zshrcfile" && check_file_has_var_defined "$zshenvfile" "DOTFILES_PATH" && check_file_has_var_defined "$zshenvfile" "SLOTH_PATH"; then
    output::solution ".Sloth loader added for \`zsh\` shell"
    return 0
  fi

  output::error "Could not add .Sloth loader or variables in ZSH files \`$zshrcfile\` & \`$zshenvfile\`"
  output::answer "Check the file, maybe add manually the loader should fix this."
  return 1
}

script::depends_on docpars

##? Adds a .Sloth loader in your current dotfiles if it was not added. If you
##? want to edit .bashrc or .zshenv, with your desired valur for DOTFILES_PATH
##? and you do not have defined yet in .bashrc, .zshenv or .zshrc, you can
##? use this script calling it with the variable DOTFILES_PATH. Example:
##?
##?   DOTFILES_PATH="${HOME}/.dotfiles" dot core loader --modify
##?
##? IMPORTANT!
##?     If your .bashrc file is not in ${HOME}/.bashrc, you can use the
##?   DEFAULT_BASHRC_FILE variable to set the path to your bashrc file. For
##?   .zshenv use DEFAULT_ZSHENV_FILE and for .zshrc use DEFAULT_ZSHRC_FILE.
##?
##? Usage:
##?   loader (-h | --help)
##?   loader (-v | --version)
##?   loader bashrc [--modify]
##?   loader zshrc [--modify]
##?   loader --modify
##?
##? Arguments:
##?   bashrc        Show or modify .bashrc content for .Sloth loading
##?   zshrc         Show or modify .zshrc and .zshenv content for .Sloth loading
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   --modify      Modify zshrc (and zshenv) or bashrc or both and append the
##?                 loader at the end if it is not. If files in \${HOME}
##?                 \`.zshenv\`, \`.zshrc\` and \`.bashrc\` does not exist they
##?                 will be created.
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
##? SCRIPT_VERSION "2.0.0"
if ! ${DOTLY_INSTALLER:-false} && package::is_installed "docpars"; then
  docs::parse "$@"
else
  version=false
  help=false
  bashrc=false
  zshrc=false
  modify=false
  while [[ $# -gt 0 ]]; do
    case "${1:-}" in
      bashrc)
        $zshrc && output::error "\`bashrc\` subcommand is not compatible with \`zshrc\` subcommand" && exit 1
        bashrc=true
        shift
        ;;
      zshrc)
        $bashrc && output::error "\`zshrc\` subcommand is not compatible with \`bashrc\` subcommand" && exit 1
        zshrc=true
        shift
        ;;
      --modify)
        modify=true
        shift
        ;;
      *)
        ! $zshrc &&
          ! $bashrc &&
          ! $modify &&
          output::error "\`--modify\` is mandatory option when no \`bashrc\` or \`zshrc\` subcommand are used" &&
          exit 1

        break 2
        ;;
    esac
  done
fi

# Print name and version or help
if ${version:-}; then
  SCRIPT_VERSION="${SCRIPT_VERSION:-$(dot::parse_script_version "$(dot::get_full_script_path)")}"
  output::write "${SCRIPT_NAME:-dot core loader} v$SCRIPT_VERSION"
  exit
elif ${help:-}; then
  grep "##?" "$(dot::get_full_script_path)" | cut -c 5-
  exit
fi

case ${1-} in
  # Any subcommand should be here
  bashrc)
    if ${modify:-false}; then
      if setup_bashrc; then
        output::answer "🏁 Restart your \`bash\` shell to have .Sloth loaded"
      else
        output::error "🚨 Something went modifing your \`.bashrc\` file"
      fi
    else
      bashrc_load
    fi
    ;;
  zshrc)
    if ${modify:-false}; then
      if setup_zsh | log::file "Setup .Sloth in .zshenv & .zshrc files"; then
        output::answer "🏁 Restart your \`zsh\` shell to have .Sloth loaded"
      else
        output::error "🚨 Something went wrong modifing your .zshrc & .zshenv file"
      fi
    else
      zshrc_load
    fi
    ;;
  *)
    if ${modify:-false}; then
      if setup_bashrc | log::file "Setup .Sloth in .bashrc file"; then
        output::answer "🏁 Restart your \`bash\` shell to have .Sloth loaded"
      else
        output::error "🚨 Something went wrong modifing your \`.bashrc\` file"
      fi

      if setup_zsh | log::file "Setup .Sloth in .zshenv & .zshrc files"; then
        output::answer "🏁 Restart your \`zsh\` shell to have .Sloth loaded"
      else
        output::error "🚨 Something went wrong modifing your .zshrc & .zshenv file"
      fi
    else
      output::error "Wrong parameters"
    fi
    ;;
esac
