#!/usr/bin/env zsh

set -euo pipefail

##### Start of Homebrew Installation Patch #####
# export HOMEBREW_SLOTH=true
# export SLOTH_PATH="HOMEBREW_PREFIX/opt/dot"
##### End of Hombrew Installation Patch #####

. "${SLOTH_PATH:-${DOTLY_PATH:-}}/scripts/core/src/_main.sh"

##? Short the current $PWD
##?
##? Usage:
##?    short_pwd
#? v1.0.0

if [[ $(pwd) == "$HOME" ]]; then
  echo "~"
else
  echo ${${${:-/${(j:/:)${(M)${(s:/:)${(D)PWD:h}}#(|.)[^.]}}/${PWD:t}}//\/~/\~}/\/\//\/}
fi
