#!/usr/bin/env zsh

##? Short the current $PWD
##?
##? Usage:
##?    short_pwd
#? v1.0.0

if [[ "$PWD" == "$HOME" ]]; then
  echo "~"
else
  echo ${${${:-/${(j:/:)${(M)${(s:/:)${(D)PWD:h}}#(|.)[^.]}}/${PWD:t}}//\/~/\~}/\/\//\/}
fi
