#!/usr/bin/env bash

set -euo pipefail

{ [[ -z "$DOTLY_PATH" ]] || [[ ! -f "${1:-}" ]]; } &&\
  echo "\033[0;31mWrong params for Dotly script call\033[0m" &&\
  exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"

DOTLY_SCRIPT_PATH="$(dirname "$1")"
DOTLY_SCRIPT_FILE_PATH="$1"
shift

_script_paths=($(echo "$DOTLY_SCRIPT_FILE_PATH" | tr "/" "\n"))
_last_script_path=$(( ${#_script_paths[@]} - 1 ))
_previous_script_path=$(( $_last_script_path - 1 ))
SCRIPT_NAME="dot ${_script_paths[$_previous_script_path]} ${_script_paths[$_last_script_path]}"
unset _script_paths _last_script_path _previous_script_path

docs::parse "$DOTLY_SCRIPT_FILE_PATH" "$@"
. "$DOTLY_SCRIPT_FILE_PATH"
