#!/usr/bin/env bash

set -euo pipefail

[[ -z "${SLOTH_PATH:-${DOTLY_PATH:-}}" ]] && exit 1

#shellcheck disable=SC1091
. "${SLOTH_PATH:-${DOTLY_PATH:-}}/scripts/core/_main.sh"
dot::load_library "git_extended.sh" "core"

##? Update dotly/sloth to the latest stable release
##?
##? Usage:
##?    update [--disable | --enable]
##?
##? Options:
##?    --disable  Deactivate the dotly update command
##?    --enable   Activate the dotly update command
##?
docs::parse "$@"

# if git::is_in_repo; then
#   echo "in"
#   git::current_commit_hash
# fi
# git::get_commit_tag
# #git::sloth_repository_exec git::get_commit_tag
# update::get_latest_minor_local_head
# exit

# if ${disable:-enable}; then
#   touch "$DOTFILES_PATH/.sloth_force_current_version"
#   exit 0
# elif ${enable:-false}; then
#   rm -f "$DOTFILES_PATH/.sloth_force_current_version"
#   exit 0
# fi

# update::update_local_sloth_module

# if [[ -f "$DOTFILES_PATH/.sloth_updated" ]]; then
#   output::answer '✅ dotly/sloth updated to the latest version'
# else
#   output::answer '👌 You already have latest dotly/sloth version'
# fi

## New part

git::get_remote_head_upstream_branch "origin" -C "${SLOTH_PATH:-$DOTLY_PATH}"