#!/usr/bin/env bash

set -euo pipefail

[[ -z "${DOTLY_PATH:-$SLOTH_PATH}" ]] && exit 1

#shellcheck disable=SC1091
. "${DOTLY_PATH:-$SLOTH_PATH}/scripts/core/src/_main.sh"

uninstall_package_output() {
  [[ -z "${1:-}" ]] && return 1
  local -r package_name="$1"
  if ! package::is_installed "$package_name"; then
    output::answer "Package \`$package_name\` is not installed"
  elif
    package::uninstall "$package_name" | log::file "Trying to remove \`$package_name\`" &&
      ! package::is_installed "$package_name"
  then
    output::answer "Package \`$package_name\` was uninstalled"
  else
    output::error "Package \`$package_name\` could not be uninstalled"
    return 1
  fi
}

##? Uninstall a package if available by using the right package manager
##?
##?
##? Usage:
##?   delete [-h | --help]
##?   delete [-v | --version]
##?   delete <packages_names>...
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
##? SCRIPT_VERSION "1.0.0"
docs::parse "$@"

if [[ -z "${packages_names[*]:-}" ]]; then
  output::error "Wrong number of params, seeing \`${SCRIPT_NAME:-} --help\`:"
  output::empty_line
  docs::parse "--help"
  exit 1
fi

output_code=0
if [[ ${#packages_names[@]} -eq 1 ]]; then
  uninstall_package_output "${packages_names[*]}" || output_code=1
else
  for package_name in "${packages_names[@]}"; do
    uninstall_package_output "$package_name" || output_code=1
  done
fi

exit $output_code
