#!/usr/bin/env bash

set -euo pipefail

[[ -z "${SLOTH_PATH:-${DOTLY_PATH:-}}" ]] && exit 1

#shellcheck disable=SC1091
. "${SLOTH_PATH:-${DOTLY_PATH:-}}/scripts/core/src/_main.sh"

##? BASH helpers
##?
##?
##? Usage:
##?   bash [-h | --help]
##?   bash [-v | --version]
##?   bash test_performance
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
##? SCRIPT_VERSION "1.0.0"
##?
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] || package::is_installed docpars; then
  docs::parse "$@"
fi

case $1 in
  "test_performance")
    PATH="${HOME}/.cargo/bin:${PATH}"
    script::depends_on hyperfine
    if platform::command_exists brew; then
      HOMBREW_PREFIX="${HOMBREW_PREFIX:-$(brew --prefix)}"
    fi

    if [[ -n "${HOMEBREW_PREFIX:-}" && -x "${HOMBREW_PREFIX}/bin/bash" ]]; then
      hyperfine '/bin/bash -i -c exit' "${HOMBREW_PREFIX}/bin/bash -i -c exit" --warmup 1
    else
      hyperfine '/bin/bash -i -c exit' --warmup 1
    fi

    output::empty_line
    output::write "ZSH INFO:"
    output::write "  💻 System BASH 📂 /bin/bash           - $(/bin/bash --version | head -n1 | awk '{print $4}')"

    if [[ -n "${HOMEBREW_PREFIX:-}" && -x "${HOMBREW_PREFIX}/bin/bash" ]]; then
      output::write "  🍺 BREW BASH   📂 ${HOMBREW_PREFIX}/bin/bash - $("${HOMBREW_PREFIX}/bin/bash" --version | head -n1 | awk '{print $4}')"
    fi

    output::empty_line
    output::write "✨ Currently using $(command -v bash) ✨"
    ;;
  *)
    exit 1
    ;;
esac