#!/usr/bin/env bash

#shellcheck disable=SC1091
. "${SLOTH_PATH:-$DOTLY_PATH}/scripts/core/src/_main.sh"

##? ZSH helpers
##?
##? Usage:
##?   zsh optimize
##?   zsh test_performance
##?   zsh reload_completions
##?   zsh clean_cache
##?   zsh fix_permissions
##?
##? Arguments:
##?   optimize
##?   test_performance     Check how much time is the loading of zsh shell
##?   reload_completions
##?   clean_cache
##?   fix_permissions      Fix error: "zsh compinit: insecure directories"
##?
##?
##? SCRIPT_VERSION "2.1.0"
docs::parse "$@"

case $1 in
  "optimize")
    output::header "Cleaning stuff"
    find "$DOTFILES_PATH/shell/zsh" -name '*.zwc' -exec rm -rf {} \;
    find "$DOTFILES_PATH/shell/zsh" -name '*.old' -exec rm -rf {} \;
    zimfw clean
    zimfw compile
    output::empty_line

    output::header "Loading zlogin"
    /bin/zsh -c ". \"${ZDOTDIR:-${HOME}}/.zlogin\""
    output::empty_line

    output::header "Reloading zsh completions"
    "$DOTLY_PATH/bin/dot" shell zsh reload_completions
    output::empty_line

    output::header "ASL only storing critical files"
    if sudo -v -B; then
      asl_conf=$(sed 's/notice] store/critical] store/g' /etc/asl.conf)
      sudo sh -c "echo '$asl_conf' > /etc/asl.conf"
      output::empty_line
    else
      output::error "This final step require elevation with sudo"
    fi
    output::solution "Done! Restart your terminal"
    ;;
  "test_performance")
    script::depends_on hyperfine
    HOMBREW_PREFIX="${HOMBREW_PREFIX:-$(brew --prefix)}"

    hyperfine '/bin/zsh -i -c exit' "${HOMBREW_PREFIX}/bin/zsh -i -c exit" --warmup 1

    echo ""
    echo "ZSH INFO:"
    echo "  🍎 macOS ZSH 📂 /bin/zsh              - $(/bin/zsh --version)"
    echo "  🍺 Brew ZSH  📂 ${HOMBREW_PREFIX}/bin/zsh - $("${HOMBREW_PREFIX}/bin/zsh" --version)"

    echo ""
    echo "✨ Currently using $(command -v zsh) ✨"
    ;;
  "clean_cache")
    find "$HOME" -name '*.zwc' -delete
    ;;
  "reload_completions")
    rm -f "$HOME/.zcompdump"
    zsh -i -c "autoload -U compaudit && autoload -Uz compinit && compinit"

    output::empty_line
    output::answer 'Now restart your terminal'
    ;;
  "fix_permissions")
    compaudit 2> /dev/null | xargs chmod -R go-w
    ;;
  *)
    exit 1
    ;;
esac
