#!/usr/bin/env bash
##? Generate a recipe for a package
##?
##?
##? Usage:
##?   recipe [-h | --help]
##?   recipe [-c | --core] [--author <author>] [--email <email>] [-o | --open] <recipe_name> [<recipe_description>...]
##?
##? Options:
##?   -h --help          Show this help
##?   -v --version       Show the program version
##?   -c --core          Create the recipe in the valid core folder for recipes in SLOTH_PATH
##?   --author <author>  Provide who is the author, if none the default git author will
##?                      be used
##?   --email <email>    Provide author email, if none the default git author email will
##?                      be used
##?   -o --open          Open editor by using env var \$EDITOR to edit or view the script if not defined just use "cat"
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
#? v1.0.0

case ${1:-} in
  # Any subcommand should be here
  *)
    output::error "Exit with error: no content yet"
    exit 1
    ;;
esac
