name: Send a Tweet when new package
on:
  registry_package:
    types: [published]
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Get release json
        run: |
          curl -sL -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" --output "release.json"
      - name: Show the file
        run: |
            cat release.json

      - name: View version and url
        run: |
            jq -r '.tag_name' "release.json"
            jq -r '.html_url' "release.json"

      - name: Set variables for making the tweet
        run: |
            PACKAGE_VERSION=$(jq -r '.tag_name' release.json)
            PACKAGE_URL=$(jq -r '.html_url' release.json)
            echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
            echo "PACKAGE_URL=$PACKAGE_URL" >> $GITHUB_ENV

      - uses: devigned/go-twitter-action@v1
        with:
          message: |
            .Sloth ${{ env.PACKAGE_VERSION }} was launched! 🚀
            You can now improve the experience of being a productivity raptor with this new version on:
            ${{ env.PACKAGE_URL }}

            Enjoy the #usrbinenvsloth!
            #dotSloth #dotfiles #productivityraptor
          apiKey: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          apiKeySecret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          accessToken: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          accessTokenSecret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
