name: Send a Tweet when new package
on:
  registry_package:
    types: [published]
  workflow_dispatch:
    inputs:
      message:
        description: 'Custom message'
        required: false
        default: 'Enjoy this new version!'

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Get release json
        run: |
          curl -sL -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" -o release.json
      
      - name: Set variables for making the tweet
        run: |
          package_body="$(jq -r '.body' "release.json")" >> $GITHUB_ENV
          package_version="$(jq -r '.tag_name' "release.json")" >> $GITHUB_ENV
          package_url="$(jq -r '.url' "release.json")" >> $GITHUB_ENV

      - uses: ethomson/send-tweet-action@v1
        with:
          status: |
            .Sloth ${{ env.package_version }} was launched! 🚀
            You can now improve the experience of being a productivity master with this new version on:
              ${{ github.api_url }}/${{ github.repository }}/releases/latest

            ${{ github.event.inputs.message }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
